// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServerDevFinalProject.Models;

#nullable disable

namespace WebServerDevFinalProject.Migrations
{
    [DbContext(typeof(HobbyContext))]
    [Migration("20260311234722_AddJaxonSeed")]
    partial class AddJaxonSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebServerDevFinalProject.Models.Jaxon", b =>
                {
                    b.Property<int>("JaxonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JaxonId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HobbyAge")
                        .HasColumnType("int");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JaxonId");

                    b.ToTable("Jaxon");

                    b.HasData(
                        new
                        {
                            JaxonId = 1,
                            Category = "Sports",
                            Description = "I like to play basketball with my friends at the park.",
                            Environment = "Outdoor",
                            HobbyAge = 10,
                            HobbyName = "Playing Basketball",
                            SkillLevel = "Beginner"
                        },
                        new
                        {
                            JaxonId = 2,
                            Category = "Gaming",
                            Description = "I like to play video games on my PlayStation with my friends.",
                            Environment = "Indoor",
                            HobbyAge = 8,
                            HobbyName = "Playing Video Games",
                            SkillLevel = "Expert"
                        });
                });

            modelBuilder.Entity("WebServerDevFinalProject.Models.Jon", b =>
                {
                    b.Property<int>("JonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JonId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Environment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HobbyAge")
                        .HasColumnType("int");

                    b.Property<string>("HobbyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("JonId");

                    b.ToTable("Jon");

                    b.HasData(
                        new
                        {
                            JonId = 1,
                            Category = "Automotive",
                            Description = "I collect sporty Hot Wheel Cars.",
                            Environment = "Indoor",
                            HobbyAge = 15,
                            HobbyName = "Hot Wheel Collecting",
                            SkillLevel = "Beginner"
                        },
                        new
                        {
                            JonId = 2,
                            Category = "Gaming",
                            Description = "I like to play first shooter games like Call of Duty on the weekends",
                            Environment = "Indoor",
                            HobbyAge = 5,
                            HobbyName = "Playing First Shooter Games",
                            SkillLevel = "Intermediate"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
